<?php

namespace Hackzilla\HackathonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallBackRepository extends EntityRepository
{
}
