<?php

namespace Hackzilla\HackathonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function matchCallback($ip)
    {
        $this->createQueryBuilder('e')
                ->select('COUNT(e.id)')
                ->where('e.ip = :ip')
                ->setParameter('ip', $ip)
                ;
        
        
        return false;
    }
}
